version: '3.8'

services:
  avbot:
    build: .
    container_name: avbot
    ports:
      - "5200:5200"
    environment:
      - CONFIG_PATH=/config/config.yml
      - TIMEZONE_DEFAULT=UTC
    volumes:
      - ./uploads:/uploads
      - ./data:/data
      - ./dialogs:/dialogs
      - ./config:/config:ro
    restart: no
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:5200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
